# Generated by Django 4.0.7 on 2022-11-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='biology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.TextField(max_length=50)),
                ('time', models.IntegerField(default=1)),
                ('teacher', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='english',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.TextField(max_length=50)),
                ('time', models.IntegerField(default=1)),
                ('teacher', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.TextField(max_length=50)),
                ('time', models.IntegerField(default=1)),
                ('teacher', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.TextField(max_length=50)),
                ('time', models.IntegerField(default=1)),
                ('teacher', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='math',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.TextField(max_length=50)),
                ('time', models.IntegerField(default=1)),
                ('teacher', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='phisics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.TextField(max_length=50)),
                ('time', models.IntegerField(default=1)),
                ('teacher', models.CharField(max_length=30)),
            ],
        ),
    ]
