# Generated by Django 4.0.7 on 2022-11-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dentist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NFP', models.CharField(max_length=50)),
                ('medcenter', models.CharField(max_length=50)),
                ('patients', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NFP', models.CharField(max_length=30)),
                ('patient', models.IntegerField(default=1)),
                ('location', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='policemen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NFP', models.CharField(max_length=50)),
                ('wtime', models.IntegerField(default=7)),
                ('age', models.IntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='stuardess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NFP', models.CharField(max_length=50)),
                ('Age', models.IntegerField(default=1)),
                ('weight', models.IntegerField(default=50)),
                ('height', models.FloatField(default=1.65)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NFP', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=17)),
                ('subject', models.CharField(max_length=30)),
                ('ball', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NFP', models.CharField(max_length=30)),
                ('job_title', models.TextField(max_length=500)),
                ('salary', models.IntegerField(default=10000000)),
                ('practice', models.CharField(max_length=30)),
            ],
        ),
    ]
